{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a9ddb2cc",
   "metadata": {},
   "source": [
    "# Metadata\n",
    "\n",
    "**Python Topics** - debugging_and_tracing\n",
    "\n",
    "**Type** - query\n",
    "\n",
    "**Target Number of Turns (User + Assistant)** - 2\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a91234b7",
   "metadata": {},
   "source": [
    "# Conversation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4ba7f4aa",
   "metadata": {},
   "source": [
    "**Assistant**\n",
    "\n",
    "Error with fish shell function\n",
    "\n",
    "```\n",
    "Ubuntu 14.04 64 bits\n",
    "fish shell v2.2.0\n",
    "The Fuck 3.2 using Python 2.7.10\n",
    "\n",
    "```\n",
    "\n",
    "```\n",
    "$ thefuck --alias\n",
    "function fuck -d \"Correct your previous console command\"\n",
    "    set -l exit_code $status\n",
    "    set -x TF_ALIAS fuck\n",
    "    set -l fucked_up_command $history[1]\n",
    "    thefuck $fucked_up_command | read -l unfucked_command\n",
    "    if [ \"$unfucked_command\" != \"\" ]\n",
    "        eval $unfucked_command\n",
    "        if test $exit_code -ne 0\n",
    "            history --delete $fucked_up_command\n",
    "            history --merge ^ /dev/null\n",
    "            return 0\n",
    "        end\n",
    "    end\n",
    "end\n",
    "```\n",
    "\n",
    "I have defined this fish function: \n",
    "\n",
    "```\n",
    "function purge \n",
    "    if test (count $argv) -gt 0\n",
    "        command sudo aptitude purge $argv; and command sudo aptitude clean -y\n",
    "        command notify-send -h int:transient:1 -t 10000 -u normal -i system-software-update \"aptitude\" \"Paquete purgado\"\n",
    "    else\n",
    "        echo \"Debe indicar el nombre del paquete/s a eliminar...\"\n",
    "    end\n",
    "end\n",
    "\n",
    "```\n",
    "\n",
    "I execute:\n",
    "\n",
    "```\n",
    "$ purge gitbook\n",
    "Couldn't find package \"gitbook\".  However, the following\n",
    "packages contain \"gitbook\" in their name:\n",
    "  gitbook-editor \n",
    "Couldn't find package \"gitbook\".  However, the following\n",
    "packages contain \"gitbook\" in their name:\n",
    "  gitbook-editor \n",
    "No packages will be installed, upgraded, or removed.\n",
    "0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n",
    "Need to get 0 B of archives. After unpacking 0 B will be used.\n",
    "\n",
    "$ fuck\n",
    "Traceback (most recent call last):\n",
    "  File \"/usr/local/bin/thefuck\", line 9, in <module>\n",
    "    load_entry_point('thefuck==3.2', 'console_scripts', 'thefuck')()\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/main.py\", line 77, in main\n",
    "    fix_command()\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/main.py\", line 22, in fix_command\n",
    "    command = types.Command.from_raw_script(sys.argv[1:])\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/types.py\", line 116, in from_raw_script\n",
    "    if cls._wait_output(result):\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/thefuck-3.2-py2.7.egg/thefuck/types.py\", line 78, in _wait_output\n",
    "    child.kill()\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/psutil/__init__.py\", line 299, in wrapper\n",
    "    return fun(self, *args, **kwargs)\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/psutil/__init__.py\", line 1089, in kill\n",
    "    self._send_signal(signal.SIGKILL)\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/psutil/__init__.py\", line 1026, in _send_signal\n",
    "    raise AccessDenied(self.pid, self._name)\n",
    "psutil.AccessDenied: psutil.AccessDenied (pid=18339)\n",
    "\n",
    "```\n",
    "\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
