{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0bc2dea4",
   "metadata": {},
   "source": [
    "# Metadata\n",
    "\n",
    "**Python Topics** - debugging_and_tracing\n",
    "\n",
    "**Type** - query\n",
    "\n",
    "**Target Number of Turns (User + Assistant)** - 2\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "47fd4133",
   "metadata": {},
   "source": [
    "# Conversation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6befbb71",
   "metadata": {},
   "source": [
    "**Assistant**\n",
    "\n",
    "cannot import name '_psutil_linux' \n",
    "\n",
    "<!-- If you have any issue with The Fuck, sorry about that, but we will do what we\r\n",
    "can to fix that. Actually, maybe we already have, so first thing to do is to\r\n",
    "update The Fuck and see if the bug is still there. -->\r\n",
    "\r\n",
    "<!-- If it is (sorry again), check if the problem has not already been reported and\r\n",
    "if not, just open an issue on [GitHub](https://github.com/nvbn/thefuck) with\r\n",
    "the following basic information: -->\r\n",
    "\r\n",
    "The output of `thefuck --version` (something like `The Fuck 3.1 using Python 3.5.0`):\r\n",
    "\r\n",
    "    thefuck --version\r\n",
    "Traceback (most recent call last):\r\n",
    "  File \"/usr/local/bin/thefuck\", line 7, in <module>\r\n",
    "    from thefuck.entrypoints.main import main\r\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/thefuck/entrypoints/main.py\", line 11, in <module>\r\n",
    "    from .alias import print_alias  # noqa: E402\r\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/thefuck/entrypoints/alias.py\", line 3, in <module>\r\n",
    "    from ..shells import shell\r\n",
    "  File \"/usr/local/lib/python3.5/dist-packages/thefuck/shells/__init__.py\", line 6, in <module>\r\n",
    "    from psutil import Process\r\n",
    "  File \"/usr/lib/python2.7/dist-packages/psutil/__init__.py\", line 68, in <module>\r\n",
    "    from . import _pslinux as _psplatform\r\n",
    "  File \"/usr/lib/python2.7/dist-packages/psutil/_pslinux.py\", line 24, in <module>\r\n",
    "    from . import _psutil_linux as cext\r\n",
    "ImportError: cannot import name '_psutil_linux'\r\n",
    "\r\n",
    "Your shell and its version (`bash`, `zsh`, *Windows PowerShell*, etc.):\r\n",
    "\r\n",
    "   bash --version\r\n",
    "GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)\r\n",
    "Copyright (C) 2013 Free Software Foundation, Inc.\r\n",
    "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\r\n",
    "\r\n",
    "This is free software; you are free to change and redistribute it.\r\n",
    "There is NO WARRANTY, to the extent permitted by law.\r\n",
    "\r\n",
    "Your system (Debian 7, ArchLinux, Windows, etc.):\r\n",
    "\r\n",
    "Ubuntu 16.04 LTS\r\n",
    "\r\n",
    "How to reproduce the bug:\r\n",
    "\r\n",
    "    typing 'fuck' or 'thefuck --version'. In short, it always gives me the same traceback of the name  import error \r\n",
    "\r\n",
    "The output of The Fuck with `THEFUCK_DEBUG=true` exported (typically execute `export THEFUCK_DEBUG=true` in your shell before The Fuck):\r\n",
    "\r\n",
    "    IDK, whatever command I use with \"thefuck\" included, same beforementioned issue \r\n",
    "\r\n",
    "If the bug only appears with a specific application, the output of that application and its version:\r\n",
    "\r\n",
    "    N/A\r\n",
    "\r\n",
    "Anything else you think is relevant:\r\n",
    "\r\n",
    "which -a python\r\n",
    "/home/antoniodn/anaconda2/bin/python\r\n",
    "/home/antoniodn/anaconda2/bin/python\r\n",
    "/usr/bin/python\r\n",
    "\r\n",
    "which -a python3\r\n",
    "/usr/bin/python3\r\n",
    "\r\n",
    "which -a pip\r\n",
    "/home/antoniodn/anaconda2/bin/pip\r\n",
    "/home/antoniodn/anaconda2/bin/pip\r\n",
    "/usr/local/bin/pip\r\n",
    "/usr/bin/pip\r\n",
    "\r\n",
    "which -a pip3\r\n",
    "/usr/local/bin/pip3\r\n",
    "/usr/bin/pip3\r\n",
    "\r\n",
    "<!-- It's only with enough information that we can do something to fix the problem. -->\r\n",
    "\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
